name: build, dockerize and push the app image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: dockerize and push to dockerhub
        uses: yuvalgersho/unleash-devops-home-exercise/templates/dockerize-and-push@v0.1
        with:
          image-tag: ${{ github.run_number }}
          username: ${{secrets.DOCKERHUB_USERNAME}}
          accesstoken: ${{secrets.DOCKERHUB_TOKEN}}
